services:
  backend:
    build:
      context: .
    container_name: app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/assembleiadb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8081:8081

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=assembleiadb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: